// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-CMrm0KNcoJ9MWmYOrg8xRELto5UkE4',
    appId: '1:749906414359:web:fceea7634492019155c552',
    messagingSenderId: '749906414359',
    projectId: 'toko-online-43157',
    authDomain: 'toko-online-43157.firebaseapp.com',
    storageBucket: 'toko-online-43157.appspot.com',
    measurementId: 'G-9EQCSMELWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0d5My7hHCSkEb3bbLzse_tpp8Ie0wv7I',
    appId: '1:749906414359:android:25e39ecb023cfb0f55c552',
    messagingSenderId: '749906414359',
    projectId: 'toko-online-43157',
    storageBucket: 'toko-online-43157.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChWQ9wPnaoKdjXWU6z0Ap-2TVCQSLZ19M',
    appId: '1:749906414359:ios:6e6557e6da970c2455c552',
    messagingSenderId: '749906414359',
    projectId: 'toko-online-43157',
    storageBucket: 'toko-online-43157.appspot.com',
    iosBundleId: 'com.example.tokoOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChWQ9wPnaoKdjXWU6z0Ap-2TVCQSLZ19M',
    appId: '1:749906414359:ios:6e6557e6da970c2455c552',
    messagingSenderId: '749906414359',
    projectId: 'toko-online-43157',
    storageBucket: 'toko-online-43157.appspot.com',
    iosBundleId: 'com.example.tokoOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW-CMrm0KNcoJ9MWmYOrg8xRELto5UkE4',
    appId: '1:749906414359:web:1ba386569df07c2b55c552',
    messagingSenderId: '749906414359',
    projectId: 'toko-online-43157',
    authDomain: 'toko-online-43157.firebaseapp.com',
    storageBucket: 'toko-online-43157.appspot.com',
    measurementId: 'G-9Z5B2VG90Y',
  );
}
